default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: '<%= ENV.fetch("DB_PASSWORD", "postgres") %>'
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  <<: *default
  database: <%= ENV.fetch("DBNAME") { "marvel_api_development" } %>

test:
  <<: *default
  database: marvel_api_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE", "marvel_api") %>
